

#         Powered by TabooLib 5.0         #


name: ${name}
main: ${main}
version: ${version}
authors:
  - IzzelAliz
  - sandtechnology
  - Bkm016

api-version: 1.13
lib-version: ${libVersion}
loader-version: ${loaderVersion}

commands:
  wayback:
    usage: /wayback
    description: /wayback

permissions:
  wayback.default:
    default: op
  wayback.rollback:
    default: op
  wayback.debug:
    default: op
  wayback.task:
    default: op
  wayback.conf:
    default: op